#!/bin/bash

# Define the directory containing the video files
VIDEO_DIR="/home/datapage/videos"

# Define the output directory for the re-encoded videos
OUTPUT_DIR="/home/datapage/videos/stream"

# Check if output directory exists, if not create it
if [ ! -d "$OUTPUT_DIR" ]; then
    mkdir -p "$OUTPUT_DIR"
fi

# Loop through each video file in the directory
for VIDEO_FILE in "$VIDEO_DIR"/*.mp4; do
    # Extract filename without extension
    FILENAME=$(basename "$VIDEO_FILE" .mp4)

    # Define output file path
    OUTPUT_FILE="$OUTPUT_DIR/${FILENAME}_converted.mp4"

    echo "Re-encoding $VIDEO_FILE to $OUTPUT_FILE"

    # Use FFmpeg to re-encode the video


ffmpeg -i "$VIDEO_FILE"  \
   -c:v libx264 -profile:v baseline -c:a aac -ar 44100 -ac 2 -b:a 128k \
   -vf format=yuv420p \
   "$OUTPUT_FILE"


#    ffmpeg -i "$VIDEO_FILE" -max_muxing_queue_size 9999 -c:v libx264 -crf 23 -maxrate 4.5M -preset faster -flags +global_header -pix_fmt yuv420p -profile:v baseline -movflags +faststart -c:a aac -ac 2 "$OUTPUT_FILE"
#    ffmpeg -i "$VIDEO_FILE" -c:v libx264 -preset medium -c:a aac -strict experimental -b:a 128k "$OUTPUT_FILE"

    # Check if FFmpeg command was successful
    if [ $? -ne 0 ]; then
        echo "Error re-encoding $VIDEO_FILE"
        exit 1
    fi
done

echo "Re-encoding completed."
