#!/bin/bash

# Define the directory containing the MP4 files
MP4_DIR="/home/datapage/videos/stream/"

# RTMPS server URL and key
RTMPS_URL_BASE="rtmps://dc1-1.rtmp.t.me/s"
STREAM_KEY="2118835890:GbzDPOKH2jKLWAZ0WHW0IQ"

# Combine the base URL with the streaming key
RTMPS_URL="${RTMPS_URL_BASE}/${STREAM_KEY}"

# Check if MP4 directory exists
if [ ! -d "$MP4_DIR" ]; then
    echo "Directory $MP4_DIR does not exist."
    exit 1
fi

# Loop indefinitely
while true; do
    # Get a list of MP4 files and shuffle them
    FILES=$(find "$MP4_DIR" -type f -name '*.mp4' | shuf)

    # Loop through shuffled files
    for FILE in $FILES; do
        echo "Streaming $FILE"

        # Stream the file using GStreamer
        gst-launch-1.0 filesrc location="$FILE" ! decodebin ! videoconvert ! x264enc bitrate=800 tune=zerolatency ! flvmux streamable=true ! rtmpsink location="$RTMPS_URL"

        # Check if gst-launch-1.0 command was successful
        if [ $? -ne 0 ]; then
            echo "Error streaming file $FILE"
            exit 1
        fi
    done
done






