#!/bin/bash

# Define the directory containing the MP4 files
VIDEO_DIR="/home/handis/Videos/stream"

# RTMPS server URL and key
RTMPS_URL="rtmps://dc1-1.rtmp.t.me/s"
STREAM_KEY="2118835890:GbzDPOKH2jKLWAZ0WHW0IQ"

# Loop indefinitely
while true; do

    # Create an array of video file paths and shuffle it
    readarray -t VIDEO_FILES < <(find "$VIDEO_DIR" -maxdepth 1 -type f -name "*.webm" | shuf)

    # Loop through each shuffled MP4 file
    for VIDEO_FILE in "${VIDEO_FILES[@]}"; do
        echo "Streaming $VIDEO_FILE"

        # Stream the video using GStreamer
        gst-launch-1.0 filesrc location="$VIDEO_FILE" ! qtdemux ! h264parse ! flvmux streamable=true ! rtmp2sink location="$RTMPS_URL/$STREAM_KEY live=1"

        # Check if gst-launch-1.0 command was successful
        if [ $? -ne 0 ]; then
            echo "Error streaming $VIDEO_FILE"
            exit 1
        fi
    done

    echo "Completed all videos. Restarting the playlist..."

done

echo "Streaming completed."
